---
title: "R Notebook"
output:
  pdf_document: default
  html_notebook: default
  html_document:
    df_print: paged
---



Try executing this chunk by clicking the *Run* button within the chunk or by placing your cursor inside it and pressing *Ctrl+Shift+Enter*. 


Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Ctrl+Alt+I*.

When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Ctrl+Shift+K* to preview the HTML file).

The preview shows you a rendered HTML copy of the contents of the editor. Consequently, unlike *Knit*, *Preview* does not run any R code chunks. Instead, the output of the chunk when it was last run in the editor is displayed.


**TOMA DE NOTAS DEL CURSO** 

4 de abril de 2025

Uno de los comandos más importantes que se tienen es el de **ALT + Enter** para lograr que una parte del código que se está haciendo en el Script se ejecute en la consola. Esta es una parte inicial pero de igual manera es bueno tenerla en cuenta.

RMD significa MarkDown de R basicamente.

El Latex que ya instalamos es lo que permite que los Markdowns por ejemplo puedan salir en PDF, de lo contrario normalmente dan error.

Desde la parte Help>Markdown Quick Reference explica qué se puede hacer, cuales son los shortcuts en los Mds para saber qué se puede hacer. Temas de Sintaxis, entre otras cosas.

Escribir ? seguido de algo EJ: "?sum" en consola, es la forma de encontrar ayuda para las funciones.

Help.Start() es la manera de conseguir información general de R, no de un paquete o función.

8 de Abril de 2025

Iniciamos con la clase 18, donde se habla de cómo instalar y cargar librerías en R.

Se explica que or ejemplo con la función para instalar paquetes de

Install.packages("Nombre_paquete", dep =TRUE)

Se da la instrucción de instalar no sólo el paquete sino todas las dependencias que tenga, por ejemplo el tidyverse que se usará mucho en el curso, tiene 8 paquetes dependientes. Lo importante es saber que dep es eso aquí.

Posteriormente cuando se quiere cargar la librería se unsa

library(Nombre_Paquete)    - En este caso sin comillas, de lo contrario no funciona

Si yo intento usar funciones que sólo existen en el paquete antes de usar library, no funciona. Por esto es fundamental.

Los paquetes también se pueden cargar dandole a la palomita de la derecha, y lo mismo para quitarlo

**Sólo hay que preocuparse cuando los rojos indiquen errores, los warnings no son tan complicados, R sólo indica que si se pudo hacer pero no del todo**

Las librerías bienen en targz cuando no se bajan del CRAN, es una forma de instalar paquetes de amigos, y por el estilo.

¿Cómo Utilizar R como una calculadora? (Clase 19)

Se pueden solicitar en la consola múltiples operaciones si van separadas con ;   esto hace que la respuesta se proporcione en vector

1+1;2+2;3+3
[1] 2
[1] 4
[1] 6

Da eso por ejemplo

%/% cociente entero (esto es básicamente aproximar hacia abajo)
%% Resto de división entera (y eso es lo que sobra de una división entera)

la separación de decimales son siempre con . en R - Jamás con ,


pi se puede escribir como tal, y R lo entiende como el número

sucede parejo con inf para infinito

NA (not available)
NaN (not a number) - indeterminación

cuand se utiliza la notación científica, la coma se mueve las posiciones que indica el e


El coeficiente biomial es la función Choose(#,#), combinatoria
se ordenan n elementos tomados de m



se usa como choose(2;3)

el factorial (!) se usa con factorial(#)


Las funciones trigonomeétricas trabajan en radianes, y las trigonométricas a la .1 son con a, asin acos y atan. Estos arcos sirven para hacer la inversa, es decir obtener el angulo en radianes de un valor.

para transformar los grados, hay que multiplicar por 180 y dividiendo por pi, es decir que pi es 180 basicamente

Recordando,

El coseno es el valor en x del triangulo que se genera con el radio (de valor 1) que hace el ángulo, mientras que el seno es el valor en el eje y

por eso para el ángulo 0, seno es 0 pero el coseno es máximo, es decir 1

la tangente es la relación entre ambas


La diferencia que no es tan evidente entre trunc y el floor es la manera en la que trata os negativos, el trunc vuelve -4,3 = -4, mientras que el floor lo lleva al más negativo, es decir que sería -5, si fueran positivos si sería igual el 4,3 sería 4 en ambos casos.

Truncar y redondear no es lo mismo entonces. Aunque es claro que parecen similares.


x<- 3+4

3+4 ->y
3+4 = y #Esto no anda

La flecha es a veces mejor porque se puede usar en los dos sentidos
En el segundo caso con el = no funcionaría

IMPORTANTE DE VARIABLES

R es sensible a las variables con mayúscula, hola y HOLA son leídas como variables diferentes

nombre_funcion = function(variable){función}
ej

cuadrado=function(x){x^2}


15 de abril de 2025


R es sensible al punt en el que se manda el comando, es decir que si el código está en varias líneas, y es tipo una función "Función", es mejor ponerle el cursor en function y no en lo escrito.


c<-function(x,y){
  x*2+y*4
}
  
  
la separación de varias instrucciones se hace con ;
ejemplo

c<-function(x,y){
  numero<-x*2+y*4;
  numero<-x*2+y*4+numero;
  numero<-x*2+y*4+numero;
  numero<-x*2+y*4+numero;
  numero
}
c(2,2)

Aquí vienen otras 2 funciones importantes, ls() y rm()

ls() #muestra las variables que estén creadas

y con rm() se eliminan variables

rm(c)

rm(list=ls()) #Esto se encarga de eliminar todo, puesto que el list lo que hace es representar digamos un vector con todo lo que pueda existir en esa variable.

También se puede utilizar la escobilla del Environment para borrar las variables..

rrr<-function(x){
  #Sumatorioa
  print("Hola")
}

rrr(10)  #Esto devuelve un texto según la función.


IMPRESIÓN DE TEXTOS EN FUNCIONES

Dentro de una function se pueden incluír prints que tienen variaciones adentro. Se resalta la siguiente

print(paste(sprintf("%i - %i =",a,b),a-b))
#lo anterior al llamar a una función con variables a y b
#la función paste lo que hace basicamente es concatenar, la otra función si lo hace es or el tema del formato



APARTADO DE NÚMEROS COMPLEJOS

Sqrt(-5)
#Esto da un error

por lo que toca utilizar 
sqrt(as.complex(-5))

complex(real=i, imaginary=sqrt(2)) -> z1
#Por ejemplo


#Recordatorio, el "Módulo" de un vector o número complejo es un simil del valor absoluto, mide el tamaño de su asociado

En el casod de los número complejos es la raíz de la suma de los cuadrados de la parte real y la imaginaria.


#TAREA

Si a las 0h del 1ero de enero de 2018 se empiezan a contar los segundos, cuánto nos demoraríamos en llegar a 250 millones de segundos

Empezamos por saber cuando es año bisiesto, fue en el 2020,


segundos<-250000000
segundosañoregular<-60*60*24*365
segundosañobisiesto<-60*60*24*366

#Años mas o menos

segundos/segundosañoregular


#Los restantes son los segundos que faltan en el año, se alcanzó a tomar 2 años bisiestos en el camino (2020 y 2024)

años<-segundos%/%((5*segundosañoregular+2*segundosañobisiesto)/7)

restantes<-(segundos%%(5*segundosañoregular+2*segundosañobisiesto))


segundosdias<-60*60*24
diasenteros<-restantes%/%segundosdias
restantes<-restantes%%segundosdias

segundoshoras<-60*60
horasenteras<-restantes%/%segundoshoras
restantes<-restantes%%segundoshoras

segundosminutos<-60
minutosenteros<-restantes%/%segundosminutos

print(años)
print(diasenteros)
print(horasenteras)
print(minutosenteros)

segundosrestantes


